  function openingCard(c, now = Date.now()) {
    const state = status(c, now);
    const octoberEnded = now >= Date.parse('2026-11-01T00:00:00+08:00');
    const detail = (title, body) => `<details class="vx-opening-detail"><summary>${escape(title)}</summary><div class="vx-opening-detail-copy">${escape(body)}</div></details>`;
    const maps = 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(c.locations.replace('1樓',''));
    const rewards = (c.rewards || []).map(r => `<article class="vx-reward" data-reward-points="${r.points}"><a class="vx-reward-art" href="/activities/rewards-2026/${escape(r.id)}.webp" target="_blank" rel="noopener" aria-label="開啟${escape(r.name)}完整活動圖"><img src="/activities/rewards-2026/${escape(r.id)}.webp" width="1122" height="1402" loading="lazy" decoding="async" alt="${escape(r.name)}，${r.points} 分兌換；${escape(r.note)}"></a><div class="vx-reward-copy"><p class="vx-reward-score"><strong>${r.points}</strong> 分 <span>POINTS</span></p><h4>${escape(r.name)}</h4><p>${escape(r.subtitle)}</p><small>${escape(r.note)}</small></div></article>`).join('');
    return `<article class="vx-campaign vx-opening" id="${escape(c.id)}" data-campaign-status="${state}">
      <div class="vx-opening-heading"><div><span class="vx-status">${names[state]}</span><h2>${escape(c.title)}</h2><p class="vx-meta">${escape(period(c))}</p></div><p class="vx-opening-tagline">風格，由你定義。</p></div>
      ${openingPicture(c)}
      <div class="vx-opening-intro"><p>從喜歡的樣子出發，讓髮型成為表達自己的一部分。<br>一次看懂預約禮遇、消費回饋、10 月專案與積分收藏。</p>${state === 'ended' ? '<p>開幕活動已結束；已取得的 The Money 仍無使用期限。</p>' : '<a class="btn btn--gold" href="https://lin.ee/Roebk7r" target="_blank" rel="noopener">LINE 預約開幕禮遇 ↗</a>'}</div>
      <nav class="vx-activity-index" aria-label="活動快速導覽"><a href="#online-booking"><span>01</span> 線上預約</a><a href="#the-money"><span>02</span> The Money</a><a href="#pride-2026"><span>03</span> 10 月彩虹專案</a><a href="#rewards-2026"><span>04</span> 積分禮遇</a></nav>
      <div class="vx-offer-grid">
        <section class="vx-offer" id="online-booking"><p class="vx-activity-kicker">01 / ONLINE BOOKING · 10–12 月</p><h3>預約你的風格</h3><p class="vx-offer-number">9<span> 折</span></p><p>透過官方線上平台預約，享開幕慶 9 折。<br>可與現行品牌優惠同享。</p></section>
        <section class="vx-offer" id="the-money"><p class="vx-activity-kicker">02 / THE MONEY · 10 月消費，11 月回饋${octoberEnded ? '（回饋累積已結束）' : ''}</p><h3>把美好留給下一次</h3><p class="vx-offer-number">10<span>% 消費代金</span></p><p>10 月在 VX ART 的實際付款總額，<br>於 11 月回饋 10% The Money。</p>${detail('回饋範圍與使用方式', c.money + '\nThe Money 為消費代金，非現金退款；與預約 9 折分開計算。')}</section>
      </div>
      <section class="vx-activity-section" id="pride-2026" data-october-status="${octoberEnded ? 'ended' : 'current'}"><div class="vx-section-heading"><div><p class="vx-activity-kicker">03 / TRIARCH × PRIDE 2026</p><h3>讓風格，成為你的宣言。</h3></div><p class="vx-meta">2026.10.01 — 10.31${octoberEnded ? ' · 已結束' : ' · 10 月限定'}</p></div><p>彩虹專案價${octoberEnded ? '（活動已結束）' : '，透過官方線上預約可再享開幕慶 9 折'}。</p><div class="vx-pride-prices">${c.prices.map((p,i) => `<section><span>${['COLOR','PERM','BLEACH'][i]}</span><h4>${escape(p.title.split('｜')[1])}</h4><strong>${escape(p.price)}</strong><p>${['色彩設計','紋理塑形','明度建構・色彩上色'][i]}<br>精準剪裁・結構修護<br>專屬洗護・質感造型</p></section>`).join('')}</div><div class="vx-pride-extras"><p><span>PRIDE STYLING</span><strong>遊行前造型整理</strong>完成作品後，遊行前皆可預約造型整理。</p><p><span>DUO SESSION</span><strong>雙人作品席次</strong>伴侶或朋友皆可一起預約。</p></div><p class="vx-activity-note">${escape(c.prideConditions).replaceAll('\n','<br>')}</p></section>
      <section class="vx-activity-section vx-rewards" id="rewards-2026"><div class="vx-section-heading"><div><p class="vx-activity-kicker">04 / VX × ERA · REWARDS COLLECTION</p><h3>把每一次喜歡，累積成禮遇。</h3></div><p class="vx-meta">15 款禮遇 · 10–50 分</p></div><p>消費集「點」，滿卡換算「分」。依喜歡的禮品與所需分數，選擇你的下一份收藏。</p>
      <div class="vx-points-guide"><div class="vx-points-table-wrap"><table class="vx-points-table"><caption>集點與滿卡換算</caption><thead><tr><th scope="col">品牌</th><th scope="col">消費集點</th><th scope="col">滿卡門檻</th><th scope="col">每張滿卡分數</th></tr></thead><tbody><tr><th scope="row">VX</th><td>每 NT$6,000＝1 點</td><td>10 點＝1 張滿點卡</td><td><strong>10 分</strong><small>VX 滿點卡＝紅卡</small></td></tr><tr><th scope="row">ERA</th><td>每 NT$3,000＝1 點</td><td>10 點＝1 張滿點卡</td><td><strong>5 分</strong><small>ERA 滿點卡＝綠卡</small></td></tr></tbody></table></div><p>「點」用來集滿卡片；「分」用來兌換禮品。<br>例：1 張 VX 滿點卡（10 分）＋1 張 ERA 滿點卡（5 分）＝15 分。</p><p class="vx-activity-note">以實際付款金額計算，使用 LINE 官方集點功能；兌換後回收相應滿點卡。</p></div>
      <p class="vx-rewards-intro"><strong>以下每一品項分別兌換，同分數品項並非整組贈送。</strong><br>圖片為商品或情境示意；款式、票券內容及詳細兌換安排，請洽門市確認。</p>
      <div class="vx-reward-filters" role="group" aria-label="依禮品分數篩選"><button type="button" data-reward-filter="all" aria-pressed="true">全部禮遇</button>${[10,15,25,35,40,50].map(p => `<button type="button" data-reward-filter="${p}" aria-pressed="false">${p} 分</button>`).join('')}</div><p class="vx-reward-count" role="status" aria-live="polite">共 15 款禮遇</p><div class="vx-reward-grid">${rewards}</div>
      <div class="vx-reward-footer"><p>選好喜歡的禮遇了嗎？<br><span>透過 LINE 告訴我們品項名稱，確認滿卡分數與兌換安排。</span></p><a class="btn btn--gold" href="https://lin.ee/Roebk7r" target="_blank" rel="noopener">LINE 詢問積分兌換 ↗</a></div></section>
      <section class="vx-opening-location"><div><span class="eyebrow">VISIT · 怎麼來 VX ART</span><h3>從這裡，開始新的風格。</h3><p>${escape(c.locations)}</p><p class="vx-meta">南京敦化路口・微風南京／IKEA 周邊</p></div><div class="button-row"><a class="btn" href="${maps}" target="_blank" rel="noopener">開啟地圖 ↗</a><a class="btn btn--gold" href="https://lin.ee/Roebk7r" target="_blank" rel="noopener">LINE 諮詢與預約 ↗</a></div></section>
    </article>`;
  }

